### ISSUE TITLE
Zeroing axes - work coordinates

### ISSUE THREAD

**Issue by meikrantz** [cheton/cnc.js#15]
Can you change the zeroing command from G10 L2 P1 to G10 L20 P1?  L20 is the appropriate behavior, setting the current position to 0, vs. L2 which sets an offset of zero from machine coordinates.

-- John

**Comment by cheton** [comment]
Thanks for correcting my mistakes. I made the bug fixes in [v0.12.5](https://github.com/cheton/cnc.js/releases), which will send `G10 L20 P1` command to set absolute position.

**Comment by meikrantz** [comment]
Perfect, thanks.
