### ISSUE TITLE
npm package dependancy issue

### ISSUE THREAD

**Issue by jarretluft** [cheton/cnc.js#18]
Hey @cheton,
Just trying to build the latest v0.13 of cnc.js and see that some dependancy that you updated recently must now require v1.17.x of the 'history' package, not v1.13.x as is currently defined in your package.json file. It would not install for me until I updated the dependancies list to the newer version.

**Comment by cheton** [comment]
Also see https://github.com/rackt/react-router/releases/tag/v1.0.3

Upgraded the `history` package from v0.13.x to v0.17.x
