### ISSUE TITLE
Small versioning request

### ISSUE THREAD

**Issue by meikrantz** [cheton/cnc.js#25]
Can you identify the version number in the web interface somewhere?  I've gotten confused a couple of times with multiple systems running :-)

**Comment by cheton** [comment]
How about adding a version string to HTML title? You can quickly check the version on browser tab.

**Comment by meikrantz** [comment]
That would work, or even something like adding it to the Settings dropdown as the first item in the list.

**Comment by cheton** [comment]
Added version number in [v0.14.6](https://github.com/cheton/cnc.js/releases/tag/v0.14.6).

You can check the version number on the browser tab, or hovering the mouse over the string of "CNC.js" on the top-left corner.

I will do several changes to the Settings dropdown in the future, so I just kept it unchanged in current version.
