### ISSUE TITLE
CNC.js gets confused by .nc file (Chilipeppr is fine)

### ISSUE THREAD

**Issue by sigxcpu76** [cheton/cnc.js#30]
It looks that the attached file confuses CNC.js 3D display. There are lots of horizontal lines which shouldn't be there. I didn't actually try to send this to the machine, just noticed the display.

Chilipeppr.com and displays it fine, Universal G-Code sender too.

[BitFan.nc.zip](https://github.com/cheton/cnc.js/files/119067/BitFan.nc.zip)

**Comment by cheton** [comment]
Thanks for reporting this issue. I will look into what went wrong with the 3D display.

**Comment by cheton** [comment]
The [gcode-toolpath](https://github.com/cheton/gcode-toolpath) module has a bug while parsing a G-code file with the following format:
```
G0 X1.1185 Y0.5562
Z0.0394
Z-0.0231
```
The X/Y position will be reset to zero at the 2nd and 3rd line.

I will fix the bug in [gcode-toolpath](https://github.com/cheton/gcode-toolpath) at first, and update the bug fixes to CNC.js as well.

**Comment by cheton** [comment]
The bug is fixed, you can check it out with [v0.15.5](https://github.com/cheton/cnc.js/releases/tag/v0.15.5).

**Comment by sigxcpu76** [comment]
I can confirm that is displayed correctly now. Thank you.
