### ISSUE TITLE
When unknown command, milling stops

### ISSUE THREAD

**Issue by SanZamoyski** [cheton/cnc.js#34]
Hi!

We are generating gcode with some program that generates unknown commands for GRBL. While using UniversalGcodeSender, we get response that this command is not recognisible and work is being continued. Haw can i prevent cnc.js from stopping after issuing not-known gcode command?

Best regards!

**Comment by cheton** [comment]
I will fix it soon. May I have your G-code sample for verification? Thanks.

**Comment by SanZamoyski** [comment]
Thank You for Your responce.
Here You are: [G-KOD.txt](https://github.com/cheton/cnc.js/files/145187/G-KOD.txt)

**Comment by cheton** [comment]
It's been fixed in [v0.15.7](https://github.com/cheton/cnc.js/releases/tag/v0.15.7). Thank you for reporting this issue.

**Comment by SanZamoyski** [comment]
Thank You!
Work like a charm.
